timezone: "Europe/Paris"
columns:
  date: "Date"
  presenter: "Presenter"
  topic: "Topic"   # still parsed but ignored for the messages, could be added in the future?
require_presenter_at_mention: true
accept_multiple_in_week: false

title: ":sparkles: WEEKLY PREZ :sparkles:"

no_presenter_templates:
  - "No one is presenting this week! Enjoy your freedom while it lasts :evil-laugh:"
  - "No presentation this week - time to chill :pepezenq:"
  - "No prez this week. See you later alligators :crocodile:"

presenter_templates:
  - "Hope you all had a fabulous weekend! :pepehappythumbsup: \n{presenter} is going to make it an even more fabulous week with their prez on {date} :slay_queen: :pepe-periodt:"
  - "Well well well... if it isn't the best team PAX has ever seen... :peepo-gold-medal: \nSpecial info just for you cuties :peepo-cutie: : don't miss {presenter}'s presentation on {date} :kermit_excited:"
  - "Howdy partners :pepe-cowboy: \nSaddle up, {presenter} is presenting on {date}! :turtle-yeehaw:"
  - "Hola team! \n{presenter} is getting ready to drop some knowledge bombs on everyone on {date} so get ready :peepo-snack: :yoyo_holding_bomb:"
  - "Hello beautiful people! :peepo-blow-kiss: \nJust a reminder that it's showtime for {presenter} on {date} :peepo-dj: :dance_vibe:"
  - "Breaking news!! :peepo-alert: \nThis week’s main event: {presenter} on {date} :peepo-omg:"
  - "Greetings earthlings :hello-alien: \nAfter scanning your primitive calendars, I can confirm {presenter} is presenting on {date}. Prepare for take-off :rocket-1:"
  - "Hmmm I can sense that your future will be very intriguing... :crystal_ball: \nAh yes, just as I suspected: \nYou have the incredible privilege of listening to {presenter} present on {date} :napoleon-dynamite-jealous-lucky:"
  - "Knock knock... :pig-hello-door: \nWho’s there? \nIt’s {presenter}!! :omg_monkey: And they're super duper excited to present on {date} :cantwait:"
  - "Dear esteemed colleagues, :fancypooh: \n \n:breakingnews: The intellectual event of the century is upon us. \n{presenter} will be presenting their genius-ness on {date} :big-brain: :ascendant:"
  - "Rise and shine team!! :rise_and_shine: \nThe forecast for {date}: \n100% chance of brilliance, courtesy of {presenter} :rainbow_spongebob:"
  - "Very real, totally legit scientists have confirmed :science_parrot: :\nListening to {presenter} on {date} increases happiness by 237%. :stonks-: :happy:"
  - "Oh you thought this week couldn’t get any better? :eyebrow_raising_meme: \n:wrong-: {presenter} is presenting on {date}, and it’s gonna be FIREEEEE :peppo_fireman::fire_burning:"
  - "Dear diary :peepo-note:\n, Today I learned {presenter} is presenting on {date} :luffy-star-struck: \nI have never been this excited in my entire life as a bot :robot-dance::spongebob-excited:\nXOXO"
  - "On {date}, {presenter} will attempt the impossible :impossible: :\nholding our collective attention for 30 minutes straight!! :peepo-eyes::shocked_scared: \nTune in to witness history :george_washington:"
  - "It’s giving... professional :businesscat: \nIt’s giving... iconic :slay: \nIt’s giving... {presenter} presenting on {date} :queen::pig-sparkle-eyes:"
  - "Once upon a time... :book::fairy::troll: \n{presenter} prepared a presentation for {date} :im_a_pretty_princess: \nAnd it was glorious. \nThe end. :fancy-peepo-happy:"

template_mode: "rotate" 

slack_user_map:
  "leo bierent": U019L5GRLT0
  "maxime vedelago": U01C73JF89E
  "solene bercu": USHV4N54K
  "nikita friche": U07UNS0E9GT
  "mehdi zemni": U07QYN88N6M
  "dana almanla": U037WMFQ9TM
  "arnoud vanhuele": U90UFUTN2
  "hamlet jesse medina ruiz": U1NJ43P3J
  "nicolas fouhety": U08JK40Q86L
  "karl toto same": U096N5UR8P6
  "aymeric philippe": U09CYPWA9B6
  "elyas benyamina": U09F1M1MNAH
  "ying-ting chen": U09TB0K803E
